### ISSUE TITLE
support fixtures

### ISSUE THREAD

**Issue by toudi** [toudi/gorpheus#1]
while not necesarily a DDL domain, it would definetely be nice / beneficial to support loading fixtures.

sample input:

```yaml
table: some_table
fixtures:
  - field_a: 'a'
    field_b: 1
  - field_a: 'c'
```

generated output:

```SQL
BEGIN;

INSERT INTO some_table (field_a, field_b) VALUES ('a', 1);
INSERT INTO some_table (field_a) VALUES ('c');

COMMIT;
```

sample input (within migration file):

```yaml
operations:
  - load-data:
      table: "some_table"
      fixtures:
        - field_a: 'a'
          field_b: 1
        - field_a: 'c'

```
